[package]
name = "butter"
version = "0.1.0"
authors = ["SamDoiron <sam.doiron96@gmail.com>"]
edition = "2018"

[dependencies]
git2 = "0.13"
anyhow = "1.0.32"
crossbeam-channel = "0.4.4"
pretty_env_logger = "0.4.0"
log = "0.4.11"